# https://hub.docker.com/_/microsoft-devcontainers-javascript-node
FROM mcr.microsoft.com/devcontainers/javascript-node:18

WORKDIR /app

COPY package.json .
COPY data/ .
RUN npm install
EXPOSE  3000
#ENTRYPOINT [ "npx json-server" ]
#ENTRYPOINT [ "/bin/bash", "-c npx", "json-server", "startrek-db.json" ]
ENTRYPOINT [ "/usr/local/bin/npx", "json-server", "startrek-db.json" ]